server:
  port: 9302
spring:
  application:
    name: cloud-payment
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

management:
  endpoints:
    web:
      exposure:
        include: "*"
