server:
  port: 9302
spring:
  application:
    name: cloud-payment
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  rabbitmq:
    username: guest
    password: guest
    port: 5672
    host: 47.100.181.79

management:
  endpoints:
    web:
      exposure:
        include: "*"
