server:
  port: 8003

spring:
  application:
    name: scs-payment

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
feign:
  client:
    config:
      PayClient:
        loggerLevel: full